'use strict';
// =============================================================
// UI文言の集約。ゲーム内の固定UIテキストはすべてここから取得する。
// 物語上のセリフ（NPC会話など）はマップデータ側に置く。
// =============================================================
const TEXT = {
  game: {
    title: 'ソラトモシ',
    subtitle: '～六灯の旅路～',
    copyright: '© 2026 Studio Hoshiakari — オリジナル作品',
  },
  title: {
    newGame: 'はじめから',
    load: 'ロード',
    settings: '設定',
    howto: 'あそびかた',
    loadFailedPixi: '描画ライブラリ（PixiJS）を読み込めませんでした。ネットワーク接続を確認して、ページを再読み込みしてください。',
  },
  cmd: {
    attack: 'たたかう',
    skill: 'スキル',
    guard: 'ぼうぎょ',
    item: 'どうぐ',
    run: 'にげる',
  },
  menu: {
    status: 'つよさ',
    item: 'どうぐ',
    equip: 'そうび',
    skill: 'スキル',
    order: '隊列',
    save: 'セーブ',
    settings: '設定',
    close: 'とじる',
    back: 'もどる',
    keyItems: '大事なもの',
    consumables: 'どうぐ',
    use: 'つかう',
    discard: 'すてる',
    equipTo: 'そうびする',
    unequip: 'はずす',
    whoUse: 'だれに つかいますか？',
    whoEquip: 'だれが そうびしますか？',
    whoCast: 'だれが つかいますか？',
    orderHelp: '入れ替えたい2人を順に選んでください。先頭ほど敵に狙われやすくなります。',
    orderFirst: '1人目を選んでください',
    orderSecond: '{name} と入れ替える相手を選んでください',
    orderDone: '隊列を入れ替えました。',
    gold: '所持金',
    playTime: 'プレイ時間',
    location: '現在地',
    noItems: 'どうぐを 何も持っていません。お店で買うか、宝箱を探しましょう。',
    noKeyItems: '大事なものは まだ持っていません。',
    noFieldSkills: 'フィールドで使えるスキルを まだ覚えていません。',
    noEquipCandidates: 'そうびできる物を持っていません。お店で買いましょう。',
    notEnoughMp: 'MPが足りません。宿屋で休むか、魔法の水で回復しましょう。',
    noEffect: 'しかし 何も起こらなかった。（効果のある相手がいません）',
    discardConfirm: '{item} を 1つ すてますか？',
    discarded: '{item} を すてた。',
    equipped: '{name} は {item} を そうびした。',
    unequipped: '{name} は {item} を はずした。',
    slotEmpty: '（なし）',
    bagFull: 'どうぐが いっぱいで はずせません。',
    orbs: 'オーブ',
    sep: '・',
    objective: '目的',
    statusLabel: '状態',
    skillsLabel: 'スキル',
    baseStat: '（素{n}）',
    reserveTag: '（待機中）',
    nextSkill: '次に覚えるスキル：Lv{lv} {skill}　（←→で仲間を切り替え）',
    allSkills: 'すべてのスキルを覚えた　（←→で仲間を切り替え）',
    elemAttr: '{e}属性',
    elemResist: '{e}耐性',
    immuneTag: '{s}無効',
    equipSummary: '{slot}：{parts}　そうび：{who}',
    battleOnlyItem: 'ここでは使えません。（戦闘中に使うどうぐです）',
    fullRestore: '{name}の HPとMPが 全回復した！',
    seedUp: '{name}の {stat}が {n} 上がった！',
    noChange: '変化なし',
    equipTitle: '{name}の そうび　{stats}',
    chooseSlotItem: '{slot}を選ぶ',
    battleOnlySkillTag: '（戦闘中のみ）',
    battleOnlySkill: '戦闘中にだけ使えるスキルです。',
    noOrderPartner: '入れ替える仲間がいません。仲間はギルドで登録できます。',
    menuHint: '（メニュー：Esc / X キー、またはMENUボタン。「目的」がいつでも確認できます）',
  },
  slot: { weapon: '武器', armor: 'よろい', shield: 'たて', acc: 'アクセ' },
  stat: {
    lv: 'Lv', hp: 'HP', mp: 'MP', maxhp: '最大HP', maxmp: '最大MP',
    atk: '攻撃力', def: '守備力', int: '魔力', agi: '素早さ', luk: '運',
    exp: '経験値', next: '次のLvまで', cls: '職業',
  },
  status: {
    poison: '毒', sleep: '眠り', paralyze: '麻痺', seal: '封印', dead: '戦闘不能',
    atkUp: '攻↑', defUp: '守↑', atkDown: '攻↓', defDown: '守↓', guard: '防御', charge: '溜め', ok: '正常',
  },
  elem: { none: '無', fire: '火', ice: '氷', thunder: '雷', wind: '風', light: '光', dark: '闇' },
  battle: {
    appear: '{name}が あらわれた！',
    appearMany: '{name}たちが あらわれた！',
    appearMixed: '魔物の群れが あらわれた！',
    bossAppear: '{name}が 立ちふさがった！',
    whoseTurn: '{name}の行動',
    chooseTarget: '対象を選んでください',
    chooseAlly: 'だれに？',
    attack: '{name}の こうげき！',
    guard: '{name}は 身を守っている。',
    damage: '{target}に {n}のダメージ！',
    damageTaken: '{target}は {n}のダメージを受けた！',
    noDamage: 'ミス！ {target}に ダメージを あたえられない！',
    miss: 'ミス！ {target}は ひらりと身をかわした！',
    crit: '会心の一撃！',
    critEnemy: '痛恨の一撃！',
    weak: '弱点を突いた！',
    resist: 'あまり効いていない…',
    immune: '{target}には 効かない！',
    absorb: '{target}は 力を吸収した！',
    defeated: '{target}を たおした！',
    allyDown: '{target}は 力つきた…',
    heal: '{target}の HPが {n}回復した！',
    healMp: '{target}の MPが {n}回復した！',
    revive: '{target}は 生き返った！',
    useSkill: '{name}は {skill}を となえた！',
    useTech: '{name}の {skill}！',
    useItem: '{name}は {item}を つかった！',
    noMp: 'しかし MPが たりない！',
    sealed: 'しかし 呪文は封じられている！',
    statusOn: '{target}は {status}状態になった！',
    statusResist: '{target}には 効かなかった。',
    statusAlready: '{target}は すでに{status}状態だ。',
    statusOff: '{target}の {status}が なおった！',
    wakeUp: '{target}は 目を覚ました！',
    asleep: '{name}は 眠っている…',
    paralyzed: '{name}は しびれて動けない！',
    poisonTick: '{name}は 毒で {n}のダメージ！',
    buff: '{target}の {stat}が 上がった！',
    debuff: '{target}の {stat}が 下がった！',
    buffEnd: '{target}の {stat}が 元に戻った。',
    cover: '{name}は {target}を かばっている！',
    covered: '{name}が {target}を かばった！',
    charge: '{name}は 気をためている！',
    steal: '{name}は {item}を ぬすんだ！',
    stealFail: 'しかし 何も ぬすめなかった。',
    runOk: 'うまく にげきれた！',
    runFail: 'しかし まわりこまれてしまった！',
    runBoss: 'この戦いからは にげられない！',
    win: '魔物たちを やっつけた！',
    winBoss: '{name}を 打ち倒した！',
    gainExp: 'それぞれ {n}ポイントの経験値を かくとく！',
    gainGold: '{n}ゴールドを 手に入れた！',
    gainItem: '{item}を 手に入れた！',
    levelUp: '{name}は レベル{lv}に 上がった！',
    learn: '{name}は {skill}を 覚えた！',
    lose: '全滅してしまった…',
    enemiesLeft: '残り {n}体',
    turnOrder: '行動順',
    prismCore: 'コア：{color}（弱点：{elem}） 次：{next}',
    prismBarrier: '結晶の障壁が 攻撃を はじいた！（弱点属性で攻めよう）',
    prismCrack: '結晶の障壁に ひびが入った！（あと{n}回）',
    prismBreak: '結晶の障壁が 砕け散った！ 今が好機だ！',
    prismReform: '結晶の障壁が 再生した…',
    prismShift: 'コアの色が {color}に 変わった！（弱点：{elem}）',
    enemyBarrierLabel: '障壁',
    enemyBrokenLabel: 'ブレイク',
    phaseChange: '{name}の 姿が 変わっていく…！',
    noTarget: '対象がいません。',
    cantAct: '行動できる仲間がいません。',
    itemGone: 'しかし 手元に なかった！',
    fled: '{name}は にげだした！',
    instakill: '急所を 捉えた！',
    wall: '{name}は 仲間の前に 立ちはだかった！',
    dispel: '味方の 能力の変化が 打ち消された！',
    allMp: '全',
    partyLabel: '味方のステータス',
    descAttack: '武器で 敵1体を攻撃する',
    descSkill: '覚えた呪文・技を使う',
    descGuard: 'このターンの被ダメージを半減する',
    descItem: 'どうぐを使う',
    descRun: '戦闘から逃げる（パーティ全員）',
    noSkills: 'まだスキルを覚えていません。',
    runLeaderOnly: '逃げる指示は先頭の仲間だけが出せます。',
    sealedNote: '（封印中は使えない）',
    brokenTurns: '／{label}：残り{n}ターン',
  },
  field: {
    chestEmpty: '宝箱は からっぽだ。',
    chestItem: '{item}を 手に入れた！',
    chestGold: '{n}ゴールドを 手に入れた！',
    chestFull: '{item}は これ以上持てないので 宝箱に残した。（最大99個）',
    locked: 'かたく鍵がかかっている。{key}が 必要なようだ。',
    unlocked: '{key}を使って 扉を開けた！',
    gateClosed: '鉄の柵が 道をふさいでいる。どこかに仕掛けがありそうだ。',
    switchOn: 'カチッ！ どこかで 何かが動く音がした。',
    rockStuck: '岩は びくともしない。（向こう側がふさがっている）',
    poisonStep: '毒のダメージ！',
    lavaStep: '溶岩の熱で ダメージを受けた！',
    swampStep: '毒の沼で ダメージを受けた！',
    springHeal: '泉の水を飲んだ。全員のHPとMPが 回復した！',
    repelOn: '灯よけの香を たいた。しばらく魔物が寄ってこない。',
    repelOff: '灯よけの香の 効き目が切れた。',
    returnWhere: 'どこへ 帰りますか？',
    returnNone: 'まだ帰れる町がありません。',
    returnDungeon: 'ここでは 帰り鳥の羽は 使えない。（屋内・ダンジョンでは使えません）',
    rock: '大きな岩だ。押せば動かせそうだ。',
    mimic: '宝箱が ガタガタと動き出した！',
    orbCount: '（オーブ {n} / 6）',
  },
  shop: {
    welcomeItem: 'いらっしゃいませ！ どうぐ屋です。',
    welcomeGear: 'いらっしゃい！ 武器と防具の店だよ。',
    buy: '買う',
    sell: '売る',
    leave: 'やめる',
    what: '何に しますか？',
    howMany: 'いくつ？（{price}G × 個数）',
    total: '合計 {n}G',
    confirmBuy: '{item}を {qty}個で {n}G です。よろしいですか？',
    confirmSell: '{item}を {qty}個 {n}G で買い取ります。よろしいですか？',
    thanks: 'まいどあり！',
    noMoney: 'お金が足りません。あと {n}G 必要です。魔物を倒して稼ぎましょう。',
    tooMany: 'これ以上持てません。（1種類につき最大99個）',
    nothingToSell: '売れる物を 持っていません。（そうび中の物と大事なものは売れません）',
    cantSell: 'それは 売ることができません。',
    equipNow: 'さっそく そうびしていきますか？',
    bye: 'またのお越しを！',
    noOneCanEquip: '（誰もそうびできない）',
    nowEquipped: '（今：{item}）',
    howManySell: '{item}を いくつ売りますか？',
    cantEquip: 'そうび不可',
    owned: '所持 {n}',
  },
  inn: {
    ask: '旅人の宿へようこそ。お一人さま {price}G、{total}G になりますが 泊まりますか？',
    noMoney: 'お金が足りないようです。あと {n}G 必要です。',
    rest: 'ゆっくりお休みください…',
    morning: 'おはようございます。全員のHPとMPが回復しました！',
    bye: 'またどうぞ。',
    speaker: '宿屋',
  },
  guild: {
    welcome: '灯守ギルドへようこそ。旅の仲間を 取りまとめています。',
    create: '仲間を登録する',
    join: 'パーティに加える',
    leave: 'パーティから外す',
    remove: '名簿から消す',
    bye: 'よい旅を！',
    rosterFull: '名簿が いっぱいです。（最大{n}人）先に誰かを名簿から消してください。',
    partyFull: 'パーティは 最大4人です。先に誰かを外してください。',
    noReserve: '待機中の仲間がいません。「仲間を登録する」で新しく迎えられます。',
    cantLeaveLast: 'パーティを空にはできません。',
    cantLeaveHero: '主人公は パーティから外せません。',
    noRemovable: '名簿から消せる仲間がいません。（パーティ外の仲間のみ消せます）',
    removeConfirm: '{name}を 名簿から消します。そうび品は どうぐ袋に戻ります。本当によろしいですか？',
    removed: '{name}は 旅立っていった…',
    joined: '{name}が パーティに加わった！',
    left: '{name}は ギルドで 待機することになった。',
    created: '{name}（{cls}）が 名簿に登録された！',
    welcomeLv: '{name}は レベル{lv}から 旅に加わります。',
    speaker: '灯守ギルド',
    askJoin: '{name}を パーティに加えますか？',
  },
  create: {
    heroTitle: '主人公の名前と職業を決めてください',
    memberTitle: '仲間 {n}人目を 決めてください',
    name: 'なまえ',
    namePlaceholder: '6文字まで',
    random: 'おまかせ',
    decide: 'けってい',
    skipRest: '残りをおまかせで決める',
    nameHelp: '名前は最大6文字。空欄なら自動で決まります。',
    preview: 'Lv1のステータス',
    confirm: '{name}（{cls}）で よろしいですか？',
    partyIntro: '旅の仲間を 決めましょう。（あとからギルドで入れ替えられます）',
    modeSelf: '自分で決める',
    modeAuto: 'おまかせで決める（おすすめ職業）',
    modeSolo: 'ひとりで旅立つ（上級者向け）',
    heroLabel: '主人公',
    memberLabel: '仲間{n}',
    nameStep: '{who}：なまえ',
    classStep: '{name}の職業',
    startEquip: '初期そうび：{items}',
    learnList: '習得：{list} …',
  },
  save: {
    slot: 'セーブ {n}',
    empty: '―― データなし ――',
    broken: '―― 壊れたデータ ――',
    saved: 'セーブしました。',
    confirmOverwrite: 'セーブ {n} に上書きしますか？',
    failed: 'セーブできませんでした。ブラウザの保存領域が使えない可能性があります。（プライベートモードの場合は通常モードでお試しください）',
    loadFailed: 'このセーブデータは壊れているため 読み込めません。別のデータを選ぶか「はじめから」で始めてください。',
    loadEmpty: 'このスロットには データがありません。',
    noData: 'セーブデータがありません。「はじめから」で始めてください。',
    loaded: 'ロードしました。',
    summaryOrbs: '{name} Lv{lv}　{map}　{time}　オーブ{orbs}',
    deleteConfirm: 'セーブ {n} を けしますか？',
    delete: 'けす',
    storageUnavailable: 'ブラウザの保存領域が使えないため、セーブと設定の保存はできません。',
  },
  settings: {
    title: '設定',
    bgm: 'BGM',
    sfx: '効果音',
    bgmVol: 'BGM音量',
    sfxVol: '効果音量',
    textSpeed: '文字の速さ',
    motion: '画面効果',
    touch: 'タッチボタン',
    on: 'ON', off: 'OFF',
    slow: 'おそい', normal: 'ふつう', fast: 'はやい', instant: '瞬間',
    auto: '自動', reduce: 'ひかえめ', full: 'フル', show: '表示', hide: '非表示',
    help: '←→で変更、決定で切替。設定は自動で保存されます。',
    close: 'とじる',
  },
  over: {
    lose: '全滅してしまった…',
    revive: '{town}で 目を覚ました。所持金が半分になった…',
  },
  howto: [
    '【キーボード】矢印キー / WASD：移動・カーソル',
    'Enter / Space / Z：決定・話す・調べる',
    'Esc / X / Backspace：キャンセル・メニューを開く',
    '【タッチ】画面下の十字キーで移動、Aで決定、Bでキャンセル、MENUでメニュー。',
    'メニューの項目は 直接タップしても選べます。',
    '町の人と話し、6つのオーブを集めて 蝕の塔を目指しましょう。',
    'セーブはメニューの「セーブ」からいつでも（戦闘中を除く）行えます。',
  ],
  ending: {
    theEnd: 'おしまい',
    trueEnd: '― 真の終わり ―',
    saveClear: 'クリアデータを セーブしますか？（裏ソラへの冒険が 続けられます）',
    saveTrue: 'クリアデータを セーブしますか？',
    toBeContinued: '世界のどこかで、新たな裂け目が 口を開けた…',
  },
  common: {
    ok: 'OK',
    yes: 'はい',
    no: 'いいえ',
    assetFallback: '一部の画像を読み込めなかったため、簡易グラフィックで表示しています。',
    unknownError: '予期しないエラーが起きました。安全のため直前の状態に戻しました。',
    webglFailed: 'このブラウザでは描画を開始できませんでした。WebGLを有効にするか、別のブラウザでお試しください。',
    minus: '1つ減らす',
    plus: '1つ増やす',
    pad: { ok: 'A', cancel: 'B', menu: 'MENU' },
  },
};

/** キーパス（'battle.damage'）からUI文言を取り出し、{name}等を置換する */
function T(path, params) {
  const parts = path.split('.');
  let v = TEXT;
  for (const p of parts) {
    if (v == null) break;
    v = v[p];
  }
  if (typeof v !== 'string') {
    console.warn('TEXT key missing:', path);
    return path;
  }
  if (!params) return v;
  return v.replace(/\{(\w+)\}/g, (m, k) => (params[k] !== undefined ? String(params[k]) : m));
}

if (typeof module !== 'undefined') module.exports = { TEXT, T };
